### PR TITLE
support mtu change

### PR DESCRIPTION
**Pull request by james-martinez**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [X] I have read the [contributing](https://github.com/linuxserver/docker-kasm/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

This PR supports Kasm deployed into Kubernetes and other virtualized networking that requires a mtu change from the dockerd default of 1500
## Benefits of this PR and context:

When Kasm deploys "workspaces" dind is used. Downloads hang and timeout and its because of the "overlayed" mtu set in the primary networking interface. eth0 (1500) -> cni0 (eg. 1450) -> docker0(1500)
## How Has This Been Tested?
Used images built in CI and verified options are passed and configured correctly. `docker inspect network bridge[hash]` and `docker exec "dev container hash" ps aux `

## Source / References:

https://blog.zespre.com/dind-mtu-size-matters.html
https://bascht.com/tech/2021/04/08/kubernetes-docker-dind-mtu-issues-on-hetzner-cloud/

### CODE REVIEW

**Comment by james-martinez** [comment]
Need to find where config if kasm network bridge kasm_default_network.
```
NETWORK ID     NAME                   DRIVER    SCOPE
353f7187f6d1   bridge                 bridge    local
3564103f2412   host                   host      local
8d3cb6e06eed   kasm_default_network   bridge    local
5ad5d5c85024   none                   null      local
```

bridge, bridge mtu options are set.
docker network inspect 353
```
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1300"
        }
```

kasm options are blank
docker network inspect 8d3
```
"Options": {}
```

**Comment by james-martinez** [comment]
Fixed issue of kasm_default_network. Now workspaces downloads content without issues.
in install.sh of kasm line 620
`docker network create --driver=bridge -o com.docker.network.driver.mtu=1300 kasm_default_network`

**Comment by james-martinez** [comment]
Kasm is able to choose which network to use, until upstream is fixed, the bridge network must be used.

Screenshot 2023-05-29 at 11 50 00 PM

**Comment by james-martinez** [comment]
Please review and merge for added feature

**Review by thelamer — APPROVED** [review]

**Pull request merged**
